"use client";
import Image from 'next/image'
import { Presentation, Landmark } from 'lucide-react' // Icons
import { motion } from 'framer-motion';

export default function Strategy() {
  return (
    <motion.section
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="grid grid-cols-1 md:grid-cols-2 gap-12 max-w-6xl mx-auto px-4">
      {/* Left Panel - Light Gray Background */}
      <motion.div
        initial={{ opacity: 0, x: -50 }}
        whileInView={{ opacity: 1, x: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="bg-gray-100 rounded-xl p-6 md:p-10 flex flex-col items-center text-center">
        {/* Logo */}
        <Image 
          src="/assets/RISE_DXB_Studio_Dark.png" 
          alt="RISE Studio Logo" 
          width={200} 
          height={80} 
          className="mb-8" 
        />
        
        {/* Main Headings with Dotted Separators */}
        <div className="w-full mb-8 ">
          <h2 className="text-xl md:text-2xl font-normal text-gray-500 mb-3">
            Financing Imagination
          </h2>
          <div className="border-b-2 border-dotted border-gray-400 mb-6"></div>
          
          <h3 className="text-xl md:text-2xl font-normal text-gray-500 mb-3">
            Producing Culture
          </h3>
          <div className="border-b-2 border-dotted border-gray-400 mb-6"></div>
        </div>

        {/* Description */}
        <p className="text-gray-500 text-sm leading-relaxed mb-8 max-w-md">
          Our Movie & Music Division operates with the full production, financing, and strategic scope of global studios, focused on developing and executing high-quality, commercially viable media IP for international consumption.
        </p>
        
        <div className="border-b-2 border-dotted border-gray-400 w-full mb-6"></div>

        {/* Production Categories */}
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          variants={{
            visible: { transition: { staggerChildren: 0.2 } },
          }}
          className="w-full space-y-6">
          <motion.div variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.5 } } }}>
            <h4 className="text-lg font-normal text-gray-500">
              Movie & Television Production
            </h4>
            <div className="border-b-2 border-dotted border-gray-400 mt-4"></div>
          </motion.div>
          
          <motion.div variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.5 } } }}>
            <h4 className="text-lg font-normal text-gray-500">
              Music & Show Production
            </h4>
            <div className="border-b-2 border-dotted border-gray-400 mt-4"></div>
          </motion.div>
          
          <motion.div variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.5 } } }}>
            <h4 className="text-lg font-normal text-gray-500">
              Live entertainment
            </h4>
          </motion.div>
        </motion.div>
      </motion.div>

      {/* Right Panel - White Background */}
      <motion.div
        initial={{ opacity: 0, x: 50 }}
        whileInView={{ opacity: 1, x: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="bg-[#f4f4f4] rounded-xl p-6 md:p-10 flex flex-col">
        {/* Strategic Model Section */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="mb-10">
          <h3 className="text-lg md:text-xl font-semibold text-gray-600 mb-6 text-center">
            Our Strategic Model
          </h3>
          
          <div className="flex flex-col items-center text-center mb-6">
            <div className="mb-4">
              <Presentation className="w-16 h-16 text-gray-600" strokeWidth={1.5} />
            </div>
            <p className="text-gray-500 text-sm leading-relaxed max-w-sm">
              We operate as a fully integrated creative house, controlling IP from initial concept to final monetization. This allows us to strategically align our productions with emerging technologies developed within our Venture Studio and promotional opportunities generated by our Events Division.
            </p>
          </div>
        </motion.div>

        {/* Financial Focus Section */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mb-auto">
          <h3 className="text-lg md:text-xl font-semibold text-gray-600 mb-6 text-center">
            Financial Focus
          </h3>
          
          <div className="flex flex-col items-center text-center mb-6">
            <div className="mb-4">
              <Landmark className="w-16 h-16 text-gray-600" strokeWidth={1.5} />
            </div>
            <p className="text-gray-500 text-sm leading-relaxed max-w-sm mb-2">
              We engage in the financing, licensing, and partnership structuring for our creative projects.
            </p>
            <p className="text-gray-500 text-sm leading-relaxed max-w-sm">
              As a division of RISE Solutions FZCO, our financial discussions relate to the capitalization of creative IP.
            </p>
          </div>
        </motion.div>

        {/* Contact Button */}
        <div className="mt-8">
          <button onClick={() => window.location.href = 'mailto:admin@risedxb.com'} className="w-full bg-gray-700 text-white py-4 rounded-lg font-semibold text-sm tracking-wide hover:bg-gray-800 transition-colors">
            CONTACT US
          </button>
        </div>
      </motion.div>
    </motion.section>
  )
}